# DEPRECATED: use config.yaml.dist and config.dev.yaml examples in the repository root.
# TODO: keep this until all references are updated.

# The base path of dex and the external name of the OpenID Connect service.
# This is the canonical URL that all clients MUST use to refer to dex. If a
# path is provided, dex's HTTP service will listen at a non-root URL.
issuer: http://builder.internal:5556/dex

# The storage configuration determines where dex stores its state. Supported
# options include SQL flavors and Kubernetes third party resources.
#
# See the documentation (https://dexidp.io/docs/storage/) for further information.
storage:
    type: sqlite3
    config:
      file: /etc/dex/dex.db

# Configuration for the HTTP endpoints.
web:
    http: 0.0.0.0:5556

# Configuration for telemetry
telemetry:
    http: 0.0.0.0:5558
    # enableProfiling: true

# Default values shown below
oauth2:
    # grantTypes determines the allowed set of authorization flows.
    grantTypes:
        - "authorization_code"
        - "client_credentials"
        - "refresh_token"
        #     - "implicit"
        #     - "password"
        - "urn:ietf:params:oauth:grant-type:device_code"
        - "urn:ietf:params:oauth:grant-type:token-exchange"
    responseTypes:
        - "code"
        - "token"
        - "id_token"

# Instead of reading from an external storage, use this list of clients.
#
# If this option isn't chosen clients may be added through the gRPC API.
staticClients:
    - id: builder-app
      redirectURIs:
          - "http://builder.internal:3000/auth/dex/callback"
      postLogoutRedirectURIs:
          - "http://builder.internal:5555/"
      name: "Builder App"
      secret: "66b2319d155f8b83b3414ebed6bb0eb717c65e97"
    - id: builder-cli
      redirectURIs:
          - "/dex/device/callback"
      postLogoutRedirectURIs:
          - "http://builder.internal:5555/"
      name: "Builder CLI"
      public: true # PKCE flow

connectors:
    - type: github
      # Required field for connector id.
      id: github
      # Required field for connector name.
      name: GitHub
      config:
          # Required fields. Dex must be pre-registered with GitHub Enterprise
          # to get the following values.
          # Credentials can be string literals or pulled from the environment.
          clientID:
          clientSecret:
          redirectURI: http://builder.internal:5556/dex/callback

          # Flag which indicates that all the user's orgs and teams should be loaded.
          # Only works if neither 'org' nor 'orgs' are specified in the config.
          loadAllGroups: false

          # How the team names are formatted
          #  - Options: 'name' (default), 'slug', 'both'.
          #  - Examples:
          #    - 'name': 'acme:Site Reliability Engineers'
          #    - 'slug': 'acme:site-reliability-engineers'
          #    - 'both': 'acme:Site Reliability Engineers', 'acme:site-reliability-engineers'
          # teamNameField: slug

          # Required ONLY for GitHub Enterprise.
          # This is the Hostname of the GitHub Enterprise account listed on the
          # management console. Ensure this domain is routable on your network.
          hostName:

          # ONLY for GitHub Enterprise. Optional field.
          # Used to support self-signed or untrusted CA root certificates.
          # rootCA: /etc/dex/ca.crt

# Let dex keep a list of passwords which can be used to login to dex.
enablePasswordDB: false

# Configuration for signing JWT tokens.
# - "local": use local keys (supports RS256 (default) and ES256)
# - "vault": use Vault Transit backend (supports RSA, ECDSA, and Ed25519)
signer:
    type: local
    config:
        keysRotationPeriod: "6h"
        algorithm: "RS256" # changes apply on the next key rotation
# signer
#   type: vault
#   config:
#     addr: http://127.0.0.1:8200
#     token: root
#     keyName: dex-key
