// Package apis provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.1 DO NOT EDIT.
package apis

import (
	"bytes"
	"compress/flate"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

// ErrorDetail defines model for ErrorDetail.
type ErrorDetail struct {
	// Location Where the error occurred, e.g. 'body.items[3].tags' or 'path.thing-id'
	Location *string `json:"location,omitempty"`

	// Message Error message text
	Message *string `json:"message,omitempty"`

	// Value The value at the given location
	Value interface{} `json:"value,omitempty"`
}

// ErrorModel defines model for ErrorModel.
type ErrorModel struct {
	// Schema A URL to the JSON Schema for this object.
	Schema *string `json:"$schema,omitempty"`

	// Detail A human-readable explanation specific to this occurrence of the problem.
	Detail *string `json:"detail,omitempty"`

	// Errors Optional list of individual error details
	Errors *[]ErrorDetail `json:"errors,omitempty"`

	// Instance A URI reference that identifies the specific occurrence of the problem.
	Instance *string `json:"instance,omitempty"`

	// Status HTTP status code
	Status *int64 `json:"status,omitempty"`

	// Title A short, human-readable summary of the problem type. This value should not change between occurrences of the error.
	Title *string `json:"title,omitempty"`

	// Type A URI reference to human-readable documentation for the error.
	Type *string `json:"type,omitempty"`
}

// openidContextKey is the context key for openid security scheme
type openidContextKey string

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"zFZfb9s2EP8qBDcgD1Nkt8324Lc2W7cUaxu0GfpQFMNJPEnsKFIlj4kdQ999OFKJY1tZu5dhT5Yl8u5+",
	"f+7IraxdPziLloJcbWWoO+whPf7ivfM/I4E2/BeU0qSdBXPp3YCeNAa5asAELOTw4NVWGlcDL+VnhaH2",
	"esh/5YcOPQrqUCBHF66uo/eoCoFlW4qTyqlNqQn78PHZp5KgDSfCeXEyAHUlddq2p1qdyELSZkC5koG8",
	"tq0cC9ljCNDiccoEQ0yfBeGa5rZfg4kzm686FOmTAEplt/oarbgHOI73sVz1GWviWCnja6fw3/L2fWb/",
	"uIzn4o93vwtyqYRX79++Ee/TStE4L6jTQeTspSwkrqEfDFfUEQ1htVhMb8ra9YtJ38WuxvJzcFYWsnG+",
	"B5IrGb2WhfQI6q01G7kiH3GGMXXvjMNau9iDPeUAUBkUuB4M2MSXCAPWutF1xsJ1ZwPYGoVrErzBu8pg",
	"vw9lom4jGueEDsLjl6g9KlFF4v+9DkHbtpyTNjktHBf6dsiyCKMDcXZtlb7WKoKZ3JkhBlnIZMkkkcdG",
	"ruR3i13b7HM6NcxYSBuNYQIOGATvYcPftQ0EtsZ5uS+ExwYzM9QBCa3Qkm40hkTTPZPfyOCcGRLKU+Pa",
	"BVT1k6fPjl1wRGYgoDhD5m9XV5cifxS1U/gw99ly+SCwtvTT2S60toQteo5NmswsG6FznopDX4XY9+A3",
	"B6gFxy3FFZsrd27oXDRKWEei7sC2KCqkG0T7gLpwFyVRss/cC1DiHX6JGGYnR37BRTcQDSOEykVaVQbs",
	"X7L4mrTuEJZydezRUm6Y3OCzdT2qaLh79VU9j6cXS4x19Jo2acTkweQGtFrxU4Xg0b+8i/rqwxUnMe4m",
	"rYNInfP6NtV+zjZIR4obchjs08SQspCuaYy2+CfUNYYwvZuy8PPgXaMTTDmOqVkYMYJCv4PBGy7UubM2",
	"157WNY5TTV6SL6I2Cr14fnkhC3mNPmQdnpTLcsnycQwYtFzJZ+Wy5BbgsyaVuwiaMCy2/PMGehz5ZYt0",
	"bNFfkQQIXieqjbDQY5nx+MTEhcpr3mvClMBDj4Q8lD5uMzROKgvJW1mfKWOaw3nS3U2R3RGxc0Kjb29P",
	"q3h7O6PwJw4RBmdD1uDpcjl/zKXqca0DBeblbHn2D+tuIKSGaly0Krsmd+MeGVwOtIxSMvQgP42FHFyY",
	"YfDcIxAGAcLiTc6hbXJ+lRWcWvpGGyPqtPjh2salNUek57D/f947CKLikZShqZIl+HFuy3MreGR6PrgC",
	"+mv0B1ep8kCO80OyZlQZi2OzL7j/wmLLDCXnD3FGt8tIU2hefndF4SDHYlzG1AEvtfnP1ShmE0z/viW4",
	"tgrXZUe9eUzrdEC8cGrDG2tnCW3iC4bB6HxdXLiakE4DeYR+d9vmp/s5XWnLuh0mKeT6dAr6GpWGq+ky",
	"8VjwNAz3gY1Hjnwy78ikJHd4HIwDhUqEmMZ0E43ZlPnyNx12j0KdjuMf0u1yD+pXr1D56pwQzFzlD+z9",
	"uAHnfD6OfwcAAP//",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
