// Package apis provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package apis

import (
	"bytes"
	"compress/flate"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
)

// CreateSiteInputBody defines model for CreateSiteInputBody.
type CreateSiteInputBody struct {
	// Schema A URL to the JSON Schema for this object.
	//
	// Example: https://example.com/schemas/CreateSiteInputBody.json
	Schema *string `json:"$schema,omitempty"`

	// Name The name of the site (e.g. fizzy-buzzy).
	//
	// Example: fizzy-buzzy
	Name string `json:"name"`
}

// DeletedAt defines model for DeletedAt.
type DeletedAt struct {
	Time  time.Time `json:"Time"`
	Valid bool      `json:"Valid"`
}

// GetSiteOutputBody defines model for GetSiteOutputBody.
type GetSiteOutputBody struct {
	// Schema A URL to the JSON Schema for this object.
	//
	// Example: https://example.com/schemas/GetSiteOutputBody.json
	Schema *string `json:"$schema,omitempty"`
	Site   Site    `json:"site"`
}

// Site defines model for Site.
type Site struct {
	// Schema A URL to the JSON Schema for this object.
	//
	// Example: https://example.com/schemas/Site.json
	Schema    *string   `json:"$schema,omitempty"`
	CreatedAt time.Time `json:"createdAt"`
	DeletedAt DeletedAt `json:"deletedAt"`

	// Id Example: 6c785b65-e689-4653-ae78-81621226c48c
	Id string `json:"id"`

	// Name Example: fizzy-buzzy
	Name      string    `json:"name"`
	UpdatedAt time.Time `json:"updatedAt"`
}

// UploadFileInputBody defines model for UploadFileInputBody.
type UploadFileInputBody struct {
	// Schema A URL to the JSON Schema for this object.
	//
	// Example: https://example.com/schemas/UploadFileInputBody.json
	Schema *string `json:"$schema,omitempty"`

	// ContentType The content type of the file.
	//
	// Example: text/plain
	ContentType string `json:"content_type"`

	// File The name of the site (e.g. fizzy-buzzy).
	//
	// Example: fizzy-buzzy
	File string `json:"file"`

	// Name The name of the site (e.g. fizzy-buzzy).
	//
	// Example: fizzy-buzzy
	Name string `json:"name"`
}

// GetSiteParams defines parameters for GetSite.
type GetSiteParams struct {
	// Name The name of the site.
	Name string `form:"name" json:"name"`
}

// UploadFileParams defines parameters for UploadFile.
type UploadFileParams struct {
	// FileName The name of the file.
	FileName string `form:"fileName" json:"fileName"`
}

// CreateSiteJSONRequestBody defines body for CreateSite for application/json ContentType.
type CreateSiteJSONRequestBody = CreateSiteInputBody

// UploadFileJSONRequestBody defines body for UploadFile for application/json ContentType.
type UploadFileJSONRequestBody = UploadFileInputBody

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"1Fffb9s2EP5XiNseNkCSf8RxXb21KVq425JicbeHIigo8RSzkEmVpJI4gf/34Uj5Ryw1TYIEyJ4skMfj",
	"3X3ffUffQK4XlVaonIX0Bmw+xwX3n0cGucNT6XCqqtq91WJJy1wI6aRWvPxkdIXGSbSQFry0GEG1s3QD",
	"vwZv9CnQ5kZWdBBSeMM+//0nc5q5ObKPpyfH7NRbskIb5ubSMp19w9wlEAFe8UVVIqQwd66yaa/XrCS5",
	"XvSaeHsdwSbfrFYQQaHNgjtIoTYSIjDIxYkql5A6U2MEblmRc+uMVOewikDxBbZDns2R0Q7ThY/aSofs",
	"N0zOE1bI6+tlnNXX18vfb0e8swOtm1YUy/daGhSQfgnXnm2sQgEonndYokPxxj2w+jMZ8tjkL7jD2NFq",
	"R9b/8FIKMm92Mq1L5KoV5iycD+Zd4X5ARzCc1O7Fk6YV6mMpQ2TwsRssIIVfetum2lxGN7Wq6Q92VfG0",
	"8fgyC0fRPbZWue/Uhs7346bY7YC7arxtlVUEgc7bhMb5q8lhNj6McTx5HY/Ghwcxx1eTeDIYDwfD4Tgf",
	"TXK4Qw/u2dYR1JV4WIZ7pJACmlt3q7Xrd7ckXez5XJWai/ey/D9Id0ewj+aWVg6V+xo2uiS8sWBksZby",
	"QpZ4O1yHV65XlVyqLnzJ/lkGxCbdjFscj+CFDacm870yt/lHgoh5baRbem4ERukKVWjJDLlB836d7Md/",
	"Z+S61Jfejtduro285pTbkRYYniW6Cm5wwWUJKUAEuihKqfArz3O0tllrbqHvyugAFcCKgpJUqjlygWab",
	"MB2YiiOtVIjd2xXaT0Lp/Om3tSwFGvbm0xQiuEBjQ9UHST/pEyjkg1cSUjhI+skBXc3d3IfbIyj81zm6",
	"NnAf0FnGA17ZkklnPY5JyMT4GkxFMPQjgVwbvkCHxkL65T5EIGc+9e81muVaWtI1pluYQ1NtG3+fEmdk",
	"bCutbMho2O/TT8MGj11VlTL3Ufd8C29elD9T7varwUPRzs7Xk835BbIMUTFKSqJICIdRf9Qu8bEO5S10",
	"rYLZYYh7T9cUk8qhUbxkFs0FGobGaMN0ntfG+BuI2PViwc0yINIgR2Ti5wSHH9sWzlYRVNp24B2eqQS5",
	"wssQl1QeqSyQLGEz0tBLWZYsaP+ubaG9TYsd29dvAyjajeg/CTxd/wVWt0WC2LN6RoY076cfkoLNuQ2U",
	"aGZmQ4l+t1w2VWKX3DKpLug52xx43X3A38FLmkFLhlfSOvuEbDrax7qDVKuokZPeDf1MxapH+mZ7tZ+g",
	"FEU368KEbZzTkfX8XsvDbTZtB/J95Gb6bl9stiNmkIkDFOJ13D8Y9ONRlvM4m0x4PMwGYzHJ+avBYLxW",
	"J5LMrTiFBB8kT9HPxHA957vEkPaOHyWIT99sXa83An/Xo84dutg6g3xx2/P2ESEVN+3RHsFV3IT5FwrJ",
	"Z2H3h86foc3369jq6ZM/qLOG/UF3K3oKU+MG4qNgtvZvgKIuy+V+a3lBRSUqLZVrjtg7mqHVdqvVfwEA",
	"AP//",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
