// Package apis provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package apis

import (
	"bytes"
	"compress/flate"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
)

// CreateSiteInputBody defines model for CreateSiteInputBody.
type CreateSiteInputBody struct {
	// Schema A URL to the JSON Schema for this object.
	//
	// Example: https://example.com/schemas/CreateSiteInputBody.json
	Schema *string `json:"$schema,omitempty"`

	// Name The name of the site (e.g. fizzy-buzzy).
	//
	// Example: fizzy-buzzy
	Name string `json:"name"`
}

// DeletedAt defines model for DeletedAt.
type DeletedAt struct {
	Time  time.Time `json:"Time"`
	Valid bool      `json:"Valid"`
}

// Site defines model for Site.
type Site struct {
	// Schema A URL to the JSON Schema for this object.
	//
	// Example: https://example.com/schemas/Site.json
	Schema    *string   `json:"$schema,omitempty"`
	CreatedAt time.Time `json:"createdAt"`
	DeletedAt DeletedAt `json:"deletedAt"`

	// Id Example: 6c785b65-e689-4653-ae78-81621226c48c
	Id string `json:"id"`

	// Name Example: fizzy-buzzy
	Name      string    `json:"name"`
	UpdatedAt time.Time `json:"updatedAt"`
}

// UploadFileInputBody defines model for UploadFileInputBody.
type UploadFileInputBody struct {
	// Schema A URL to the JSON Schema for this object.
	//
	// Example: https://example.com/schemas/UploadFileInputBody.json
	Schema *string `json:"$schema,omitempty"`

	// ContentType The content type of the file.
	//
	// Example: text/plain
	ContentType string `json:"content_type"`

	// File The name of the site (e.g. fizzy-buzzy).
	//
	// Example: fizzy-buzzy
	File string `json:"file"`

	// Name The name of the site (e.g. fizzy-buzzy).
	//
	// Example: fizzy-buzzy
	Name string `json:"name"`
}

// QuerySiteParams defines parameters for QuerySite.
type QuerySiteParams struct {
	// Name The name of the site.
	Name string `form:"name" json:"name"`
}

// UploadFileParams defines parameters for UploadFile.
type UploadFileParams struct {
	// FileName The name of the file.
	FileName string `form:"fileName" json:"fileName"`
}

// QuerySiteJSONRequestBody defines body for QuerySite for application/json ContentType.
type QuerySiteJSONRequestBody = CreateSiteInputBody

// CreateSiteJSONRequestBody defines body for CreateSite for application/json ContentType.
type CreateSiteJSONRequestBody = CreateSiteInputBody

// UploadFileJSONRequestBody defines body for UploadFile for application/json ContentType.
type UploadFileJSONRequestBody = UploadFileInputBody

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"5Fbfb9s2EP5XiFsfNkDyrziOo7c0RQF3W9It7vZQBAUlnmIWNKmQVBIn8P8+HCn/iK21SdECGfYkgTwe",
	"v7v77uM9QGHmldGovYPsAVwxwzkPv6cWuccL6XGiq9q/NmJBy1wI6aXRXL23pkLrJTrISq4cJlBtLT3A",
	"q+iNfgW6wsqKDkIGJ+zDn78xb5ifIXt3cX7GLoIlK41lfiYdM/lnLHwHEsA7Pq8UQgYz7yuXdbvNSqcw",
	"826Dt9sCtvPZGQ0JlMbOuYcMaishAYtcnGu1gMzbGhPwi4qcO2+lvoJlAprPcR/ydIaMdpgpA2onPbKf",
	"sXPVYaW8v1+keX1/v/jlMeKtHdi7aUlYrmtpUUD2MV57ubaKCSA8b1ChR3Hin5n9qYxxrOMX3GPqabUl",
	"6r+4koLMm53cGIVc78GcxvPRvA0u1eDl8oTQfSsxisCxphBPy6rYrt0riyVk8FN303JrXJsiLxOIhdgE",
	"NCqOxof56DDF0fg4HY4OD1KOR+N03B8N+oPBqBiOC/gCk59IyATqSjwvwh1ySAHNrdvZ2va7nZI29nyo",
	"lOHirVT/BdFpAfvN3DLao/af4kab+DQWjCxWIlRKhY/herzz3UpxqdvqS/Y/RNrW4ebc4WgIL0xWm8h3",
	"0rzPv2UCDovaSr8I3IiMMhXq2JI5cov27SrYd39PybUyt8GO135mrLznFNupERgfVFNFNzjnUkEGkIAp",
	"SyU1fuJFgc41a80t9F9ZE0sFsCRQklI1Qy7QbgKmAxNxarSO2INdaYKGSx9Ov66lEmjZyfsJJHCD1sWs",
	"9zu9To+KQj54JSGDg06vc0BXcz8LcLtUivB3hX6/cH/UaCU6xpUKRXNM6lDBPN7ZiSHZkIyJaE4swutA",
	"t1g+R4/WQfbxKZwgdyEL1+RlpTLZqrybisf+2mjALjsuozG6tbY0nAgVrColiwC5Gxp5PRF9Tb/bhqXl",
	"Yy4SsrDgKqNdTO2g1/tuEEJqw5376YwVmvEbZDmiZteheqJDHBj2hvvlPTOxFUtT62h2GKHuaKpmUnu0",
	"mivm0N6gZWitscwURW1tuIGaqp7PuV2sSBDhEJP5FREgzAwOLpcJVMa1kC1m1zHONN5GYDtsY1MS8Fup",
	"FIsPz7ZtadoZuSka/G9ZwWbcRU40D3bDiV67VjdZYrecGv6GpsDmwHH7gXAHV/QALhjeSefdd6TT6W6t",
	"W0i1TBot6z7QZyKWXRJX163D800o2lkXn/fGOR1ZDQ8rQXrMps008BSBm7zZlbfN+9bPxQEKcZz2Dvq9",
	"dJgXPM3HY54O8v5IjAt+1O+PVnpIer2RwxjgswQx+Zr8roaMNvmlvbMXIsFtoyMVf9ujKTz61HmLfP7Y",
	"82aCkZrb/bkigbu0gfk7Csmncfdfnf+ANt/N415Pn/9KnTXo9dtbMVCYGjcSHwVzdRhAylqpxW5rBUFF",
	"LSojtW+OuC80w17bLZf/BAAA//8=",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
