components:
  schemas:
    CreateSiteInputBody:
      additionalProperties: false
      properties:
        $schema:
          description: A URL to the JSON Schema for this object.
          example: https://example.com/schemas/CreateSiteInputBody.json
          format: uri
          readOnly: true
          type: string
        name:
          description: The name of the site (e.g. fizzy-buzzy).
          example: fizzy-buzzy
          type: string
      required:
        - name
      type: object
    DeletedAt:
      additionalProperties: false
      properties:
        Time:
          format: date-time
          type: string
        Valid:
          type: boolean
      required:
        - Time
        - Valid
      type: object
    ErrorDetail:
      additionalProperties: false
      properties:
        location:
          description: Where the error occurred, e.g. 'body.items[3].tags' or 'path.thing-id'
          type: string
        message:
          description: Error message text
          type: string
        value:
          description: The value at the given location
      type: object
    ErrorModel:
      additionalProperties: false
      properties:
        detail:
          description: A human-readable explanation specific to this occurrence of the problem.
          example: Property foo is required but is missing.
          type: string
        errors:
          description: Optional list of individual error details
          items:
            $ref: "#/components/schemas/ErrorDetail"
          nullable: true
          type: array
        instance:
          description: A URI reference that identifies the specific occurrence of the problem.
          example: https://example.com/error-log/abc123
          format: uri
          type: string
        status:
          description: HTTP status code
          example: 400
          format: int64
          type: integer
        title:
          description: A short, human-readable summary of the problem type. This value should not change between occurrences of the error.
          example: Bad Request
          type: string
        type:
          default: about:blank
          description: A URI reference to human-readable documentation for the error.
          example: https://example.com/errors/example
          format: uri
          type: string
      type: object
    Site:
      additionalProperties: false
      properties:
        $schema:
          description: A URL to the JSON Schema for this object.
          example: https://example.com/schemas/Site.json
          format: uri
          readOnly: true
          type: string
        createdAt:
          format: date-time
          type: string
        deletedAt:
          $ref: "#/components/schemas/DeletedAt"
        id:
          example: 6c785b65-e689-4653-ae78-81621226c48c
          type: string
        name:
          example: fizzy-buzzy
          type: string
        updatedAt:
          format: date-time
          type: string
      required:
        - id
        - name
        - createdAt
        - updatedAt
        - deletedAt
      type: object
  securitySchemes:
    openid:
      bearerFormat: JWT
      flows:
        authorizationCode:
          scopes:
            email: ""
            offline_access: ""
            openid: ""
            profile: ""
          tokenUrl: ""
      in: header
      type: openIdConnect
info:
  title: Builder API
  version: 1.0.0
openapi: 3.0.3
paths:
  /sites:
    post:
      description: Creates a new site in the builder. This will create a new site folder.
      operationId: createSite
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateSiteInputBody"
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Site"
          description: The site has been created.
        "400":
          description: The request was invalid.
        "409":
          description: The site already exists.
        "500":
          description: An internal server error occurred.
      summary: Create a new site
      tags:
        - Sites

